### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by DewanPieterse** [PaulStoffregen/Arduino-1.9.0-beta34-Teensyduino#1]
Hi Paul

I am trying to build Arduino with terminal (MacOS 10.15.0) and I keep getting an error.

When I try to build, I enter 1.9.0-beta and it takes about 2:30 and the build fails. It complains about a failed checksum.

`File ./arduino-builder-macosx-1.3.25-PR250.tar.bz2 failed checksum.
      Please remove "./arduino-builder-macosx-1.3.25-PR250.tar.bz2" to download it again.`

Any suggestions?

**Comment by PaulStoffregen** [comment]
This is a modified copy for Teensy.  If you're trying to build a full Arduino IDE, get the original source from Arduino.

If you use this modified copy, it builds only the JAR files.  Then you just copy PDE.JAR and ARDUINO-CORE.JAR into the copy of Arduino with Teensyduino already installed.
